/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ecoapp;

/**
 *
 * @author sahee
 */
public class buying extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(buying.class.getName());

    /**
     * Creates new form buying
     */
    public buying() {
        initComponents();
        this.setLocationRelativeTo(null); // senter frame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        ecoin = new javax.swing.JLabel();
        bestreccord = new javax.swing.JLabel();
        btback = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        foodtype1 = new javax.swing.JComboBox<>();
        btdistance = new javax.swing.JSpinner();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        calculatefood = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        btbuying = new javax.swing.JButton();
        btwaste = new javax.swing.JButton();
        bttransportation = new javax.swing.JButton();
        btliving = new javax.swing.JButton();
        btfood = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ecoin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ecoin.setText("1000");
        getContentPane().add(ecoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        bestreccord.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bestreccord.setText("1000");
        getContentPane().add(bestreccord, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        btback.setIcon(new javax.swing.ImageIcon("C:\\Users\\sahee\\OneDrive\\Pictures\\โฟลเดอร์ใหม่\\HOme.png")); // NOI18N
        btback.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });
        getContentPane().add(btback, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, 50));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\sahee\\OneDrive\\Pictures\\โฟลเดอร์ใหม่\\SHOP.png")); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 10, -1, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 0));
        jLabel7.setText("Second hand ?");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        foodtype1.setBackground(new java.awt.Color(153, 255, 153));
        foodtype1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        foodtype1.setForeground(new java.awt.Color(51, 102, 0));
        foodtype1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chicken", "beef", "pork", "vegetable", "rice" }));
        foodtype1.setOpaque(true);
        foodtype1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodtype1ActionPerformed(evt);
            }
        });
        getContentPane().add(foodtype1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 120, -1));

        btdistance.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(btdistance, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 100, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Yes");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("No");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 0));
        jLabel8.setText(" Purcheses/day");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 0));
        jLabel9.setText("Product type");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("No");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setText("Yes");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 0));
        jLabel10.setText("Re use ?");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        buttonGroup3.add(jRadioButton4);
        jRadioButton4.setText("No");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, -1));

        buttonGroup3.add(jRadioButton6);
        jRadioButton6.setText("Yes");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 0));
        jLabel11.setText("Use  a cloth bag ?");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        calculatefood.setBackground(new java.awt.Color(51, 204, 0));
        calculatefood.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        calculatefood.setForeground(new java.awt.Color(255, 255, 255));
        calculatefood.setText("Calculate");
        calculatefood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatefoodActionPerformed(evt);
            }
        });
        getContentPane().add(calculatefood, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, 30));

        remove.setBackground(new java.awt.Color(255, 102, 102));
        remove.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        remove.setForeground(new java.awt.Color(255, 255, 255));
        remove.setText("remove");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        getContentPane().add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, -1, 30));

        btbuying.setBackground(new java.awt.Color(0, 102, 51));
        btbuying.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btbuying.setForeground(new java.awt.Color(255, 255, 255));
        btbuying.setText("BUYING");
        btbuying.setActionCommand("TRANSPORT");
        btbuying.setEnabled(false);
        btbuying.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbuyingActionPerformed(evt);
            }
        });
        getContentPane().add(btbuying, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 130, 50));

        btwaste.setBackground(new java.awt.Color(0, 102, 51));
        btwaste.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btwaste.setForeground(new java.awt.Color(255, 255, 255));
        btwaste.setText("WASTE");
        btwaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btwasteActionPerformed(evt);
            }
        });
        getContentPane().add(btwaste, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 80, 50));

        bttransportation.setBackground(new java.awt.Color(0, 102, 51));
        bttransportation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bttransportation.setForeground(new java.awt.Color(255, 255, 255));
        bttransportation.setText("TRANSPORT");
        bttransportation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttransportationActionPerformed(evt);
            }
        });
        getContentPane().add(bttransportation, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 110, 50));

        btliving.setBackground(new java.awt.Color(0, 102, 51));
        btliving.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btliving.setForeground(new java.awt.Color(255, 255, 255));
        btliving.setText("LIVING");
        btliving.setActionCommand("TRANSPORT");
        btliving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlivingActionPerformed(evt);
            }
        });
        getContentPane().add(btliving, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 90, 50));

        btfood.setBackground(new java.awt.Color(0, 102, 51));
        btfood.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btfood.setForeground(new java.awt.Color(255, 255, 255));
        btfood.setText("FOOD");
        btfood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfoodActionPerformed(evt);
            }
        });
        getContentPane().add(btfood, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 80, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\sahee\\OneDrive\\Pictures\\โฟลเดอร์ใหม่\\BUYING.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        mainmenu main = new mainmenu();     // กลับไปหน้าแรก
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btbackActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void foodtype1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodtype1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodtype1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void calculatefoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatefoodActionPerformed
        String selectedFood = foodtype.getSelectedItem().toString();
        double efType;
        switch (selectedFood) {
            case "chicken":
            efType = 6.9;
            break;
            case "beef":
            efType = 27.0;
            break;
            case "pork":
            efType = 12.1;
            break;
            case "vegetable":
            efType = 2.0;
            break;
            default:
            efType = 0.0;
        }
        System.out.print(efType);
    }//GEN-LAST:event_calculatefoodActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeActionPerformed

    private void btbuyingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbuyingActionPerformed
        buying nextFrame = new buying();
        nextFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btbuyingActionPerformed

    private void btwasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btwasteActionPerformed
        wasted nextFrame = new wasted();
        nextFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btwasteActionPerformed

    private void bttransportationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttransportationActionPerformed
        transport nextFrame = new transport();
        nextFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttransportationActionPerformed

    private void btlivingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlivingActionPerformed
        living nextFrame = new living();
        nextFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btlivingActionPerformed

    private void btfoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfoodActionPerformed
        Food nextFrame = new Food();
        nextFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btfoodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new buying().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bestreccord;
    private javax.swing.JButton btback;
    private javax.swing.JButton btbuying;
    private javax.swing.JSpinner btdistance;
    private javax.swing.JButton btfood;
    private javax.swing.JButton btliving;
    private javax.swing.JButton bttransportation;
    private javax.swing.JButton btwaste;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton calculatefood;
    private javax.swing.JLabel ecoin;
    private javax.swing.JComboBox<String> foodtype1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JButton remove;
    // End of variables declaration//GEN-END:variables
}
