/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ecoapp;

/**
 *
 * @author sahee
 */
public class Food extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Food.class.getName());

    /**
     * Creates new form test
     */
    public Food() {
        initComponents();
        this.setLocationRelativeTo(null); // senter frame
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ecoin = new javax.swing.JLabel();
        bestreccord = new javax.swing.JLabel();
        btback = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        packaging = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        quantitymeal = new javax.swing.JLabel();
        freguencyfood = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        quantityfood = new javax.swing.JSpinner();
        quantitymeal1 = new javax.swing.JLabel();
        foodtype = new javax.swing.JComboBox<>();
        quantitymeal2 = new javax.swing.JLabel();
        foodwaste = new javax.swing.JSlider();
        btcalculatefood = new javax.swing.JButton();
        btremovefood = new javax.swing.JButton();
        btbuying = new javax.swing.JButton();
        btwaste = new javax.swing.JButton();
        bttransportation = new javax.swing.JButton();
        btliving = new javax.swing.JButton();
        btfood = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ecoin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ecoin.setText("1000");
        getContentPane().add(ecoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        bestreccord.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bestreccord.setText("1000");
        getContentPane().add(bestreccord, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        btback.setIcon(new javax.swing.ImageIcon("C:\\Users\\sahee\\OneDrive\\Pictures\\โฟลเดอร์ใหม่\\HOme.png")); // NOI18N
        btback.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });
        getContentPane().add(btback, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, 50));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\sahee\\OneDrive\\Pictures\\โฟลเดอร์ใหม่\\SHOP.png")); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 10, -1, 50));

        packaging.setBackground(new java.awt.Color(153, 255, 153));
        packaging.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        packaging.setForeground(new java.awt.Color(51, 102, 0));
        packaging.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "plastic", "paper" }));
        packaging.setOpaque(true);
        packaging.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packagingActionPerformed(evt);
            }
        });
        getContentPane().add(packaging, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 120, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 0));
        jLabel5.setText("Freaguency (meals/day)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        quantitymeal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quantitymeal.setForeground(new java.awt.Color(0, 102, 0));
        quantitymeal.setText("Food wasted%");
        getContentPane().add(quantitymeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, -1));

        freguencyfood.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(freguencyfood, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 120, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 0));
        jLabel6.setText("Food type");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        quantityfood.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(quantityfood, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 100, -1));

        quantitymeal1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quantitymeal1.setForeground(new java.awt.Color(0, 102, 0));
        quantitymeal1.setText("Quantity (g/meal)");
        getContentPane().add(quantitymeal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        foodtype.setBackground(new java.awt.Color(153, 255, 153));
        foodtype.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        foodtype.setForeground(new java.awt.Color(51, 102, 0));
        foodtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chicken", "beef", "pork", "vegetable", "rice" }));
        foodtype.setOpaque(true);
        foodtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodtypeActionPerformed(evt);
            }
        });
        getContentPane().add(foodtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 120, -1));

        quantitymeal2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        quantitymeal2.setForeground(new java.awt.Color(0, 102, 0));
        quantitymeal2.setText("Packaging");
        getContentPane().add(quantitymeal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        foodwaste.setMajorTickSpacing(10);
        foodwaste.setMinorTickSpacing(1);
        foodwaste.setPaintLabels(true);
        foodwaste.setPaintTicks(true);
        foodwaste.setValue(100);
        getContentPane().add(foodwaste, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 310, -1));

        btcalculatefood.setBackground(new java.awt.Color(51, 204, 0));
        btcalculatefood.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btcalculatefood.setForeground(new java.awt.Color(255, 255, 255));
        btcalculatefood.setText("Calculate");
        btcalculatefood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcalculatefoodActionPerformed(evt);
            }
        });
        getContentPane().add(btcalculatefood, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, 30));

        btremovefood.setBackground(new java.awt.Color(255, 102, 102));
        btremovefood.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btremovefood.setForeground(new java.awt.Color(255, 255, 255));
        btremovefood.setText("remove");
        btremovefood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btremovefoodActionPerformed(evt);
            }
        });
        getContentPane().add(btremovefood, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, -1, 30));

        btbuying.setBackground(new java.awt.Color(0, 102, 51));
        btbuying.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btbuying.setForeground(new java.awt.Color(255, 255, 255));
        btbuying.setText("BUYING");
        btbuying.setActionCommand("TRANSPORT");
        btbuying.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbuyingActionPerformed(evt);
            }
        });
        getContentPane().add(btbuying, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 130, 50));

        btwaste.setBackground(new java.awt.Color(0, 102, 51));
        btwaste.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btwaste.setForeground(new java.awt.Color(255, 255, 255));
        btwaste.setText("WASTE");
        btwaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btwasteActionPerformed(evt);
            }
        });
        getContentPane().add(btwaste, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 80, 50));

        bttransportation.setBackground(new java.awt.Color(0, 102, 51));
        bttransportation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bttransportation.setForeground(new java.awt.Color(255, 255, 255));
        bttransportation.setText("TRANSPORT");
        bttransportation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttransportationActionPerformed(evt);
            }
        });
        getContentPane().add(bttransportation, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 110, 50));

        btliving.setBackground(new java.awt.Color(0, 102, 51));
        btliving.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btliving.setForeground(new java.awt.Color(255, 255, 255));
        btliving.setText("LIVING");
        btliving.setActionCommand("TRANSPORT");
        btliving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlivingActionPerformed(evt);
            }
        });
        getContentPane().add(btliving, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 90, 50));

        btfood.setBackground(new java.awt.Color(0, 102, 51));
        btfood.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btfood.setForeground(new java.awt.Color(255, 255, 255));
        btfood.setText("FOOD");
        btfood.setEnabled(false);
        btfood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfoodActionPerformed(evt);
            }
        });
        getContentPane().add(btfood, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 80, 50));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\sahee\\OneDrive\\Pictures\\โฟลเดอร์ใหม่\\Food (1).png")); // NOI18N
        jLabel2.setText("1000");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        mainmenu main = new mainmenu();     // กลับไปหน้าแรก
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btbackActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void packagingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packagingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_packagingActionPerformed

    private void foodtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foodtypeActionPerformed

    private void btcalculatefoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcalculatefoodActionPerformed
        String selectedFood = foodtype.getSelectedItem().toString();
        double efType;
        switch (selectedFood) {
            case "chicken":
                efType = 6.9;
                break;
            case "beef":
                efType = 27.0;
                break;
            case "pork":
                efType = 12.1;
                break;
            case "vegetable":
                efType = 2.0;
                break;
            default:
                efType = 0.0;
        }
        System.out.print(efType);
    }//GEN-LAST:event_btcalculatefoodActionPerformed

    private void btremovefoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btremovefoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btremovefoodActionPerformed

    private void btbuyingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbuyingActionPerformed
        buying nextFrame = new buying();
        nextFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btbuyingActionPerformed

    private void btwasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btwasteActionPerformed
        wasted nextFrame = new wasted();
        nextFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btwasteActionPerformed

    private void bttransportationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttransportationActionPerformed
        transport nextFrame = new transport();
        nextFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttransportationActionPerformed

    private void btlivingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlivingActionPerformed
        living nextFrame = new living();
        nextFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btlivingActionPerformed

    private void btfoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfoodActionPerformed
        Food nextFrame = new Food();
        nextFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btfoodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Food().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bestreccord;
    private javax.swing.JButton btback;
    private javax.swing.JButton btbuying;
    private javax.swing.JButton btcalculatefood;
    private javax.swing.JButton btfood;
    private javax.swing.JButton btliving;
    private javax.swing.JButton btremovefood;
    private javax.swing.JButton bttransportation;
    private javax.swing.JButton btwaste;
    private javax.swing.JLabel ecoin;
    private javax.swing.JComboBox<String> foodtype;
    private javax.swing.JSlider foodwaste;
    private javax.swing.JSpinner freguencyfood;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> packaging;
    private javax.swing.JSpinner quantityfood;
    private javax.swing.JLabel quantitymeal;
    private javax.swing.JLabel quantitymeal1;
    private javax.swing.JLabel quantitymeal2;
    // End of variables declaration//GEN-END:variables
}
