/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ecoapp;

import java.awt.Color;
import javax.swing.JProgressBar;
import javax.swing.UIManager;


/**
 *
 * @author sahee
 */
public class mainmenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mainmenu.class.getName());

    /**
     * Creates new form mainmenu
     */
    public mainmenu() {
        initComponents();
        this.setLocationRelativeTo(null); // senter frame
        setNimbusColor(jProgressBarwater, new Color(255, 0, 0)); // แดง
        setNimbusColor(jProgressBarHp, new Color(0, 200, 0)); // เขียว
        
    }
    
    private void setNimbusColor(JProgressBar bar, Color color) {
    Color oldColor = (Color) UIManager.get("nimbusOrange");
    UIManager.put("nimbusOrange", color);
    bar.updateUI();
    UIManager.put("nimbusOrange", oldColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btbuying = new javax.swing.JButton();
        btwaste = new javax.swing.JButton();
        bttransportation = new javax.swing.JButton();
        btliving = new javax.swing.JButton();
        btfood = new javax.swing.JButton();
        ecoin = new javax.swing.JLabel();
        bestreccord = new javax.swing.JLabel();
        history = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jProgressBarwater = new javax.swing.JProgressBar();
        jProgressBarHp = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btbuying.setBackground(new java.awt.Color(0, 102, 51));
        btbuying.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btbuying.setForeground(new java.awt.Color(255, 255, 255));
        btbuying.setText("BUYING");
        btbuying.setActionCommand("TRANSPORT");
        btbuying.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbuyingActionPerformed(evt);
            }
        });
        getContentPane().add(btbuying, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 130, 50));

        btwaste.setBackground(new java.awt.Color(0, 102, 51));
        btwaste.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btwaste.setForeground(new java.awt.Color(255, 255, 255));
        btwaste.setText("WASTE");
        btwaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btwasteActionPerformed(evt);
            }
        });
        getContentPane().add(btwaste, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 80, 50));

        bttransportation.setBackground(new java.awt.Color(0, 102, 51));
        bttransportation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bttransportation.setForeground(new java.awt.Color(255, 255, 255));
        bttransportation.setText("TRANSPORT");
        bttransportation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttransportationActionPerformed(evt);
            }
        });
        getContentPane().add(bttransportation, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 110, 50));

        btliving.setBackground(new java.awt.Color(0, 102, 51));
        btliving.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btliving.setForeground(new java.awt.Color(255, 255, 255));
        btliving.setText("LIVING");
        btliving.setActionCommand("TRANSPORT");
        btliving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlivingActionPerformed(evt);
            }
        });
        getContentPane().add(btliving, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 90, 50));

        btfood.setBackground(new java.awt.Color(0, 102, 51));
        btfood.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btfood.setForeground(new java.awt.Color(255, 255, 255));
        btfood.setText("FOOD");
        btfood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfoodActionPerformed(evt);
            }
        });
        getContentPane().add(btfood, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 80, 50));

        ecoin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ecoin.setText("1000");
        getContentPane().add(ecoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        bestreccord.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bestreccord.setText("1000");
        getContentPane().add(bestreccord, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        history.setIcon(new javax.swing.ImageIcon("C:\\Users\\sahee\\OneDrive\\Pictures\\โฟลเดอร์ใหม่\\history.png")); // NOI18N
        history.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyActionPerformed(evt);
            }
        });
        getContentPane().add(history, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, 50));

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\sahee\\OneDrive\\Pictures\\โฟลเดอร์ใหม่\\vegetable.png")); // NOI18N
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, 50));

        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\sahee\\OneDrive\\Pictures\\โฟลเดอร์ใหม่\\SHOP.png")); // NOI18N
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 10, -1, 50));

        jButton6.setIcon(new javax.swing.ImageIcon("C:\\Users\\sahee\\OneDrive\\Pictures\\โฟลเดอร์ใหม่\\water.png")); // NOI18N
        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, 50));

        jButton7.setIcon(new javax.swing.ImageIcon("C:\\Users\\sahee\\OneDrive\\Pictures\\โฟลเดอร์ใหม่\\meal.png")); // NOI18N
        jButton7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, 50));

        jLabel1.setText("10");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        jLabel3.setText("10");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        jLabel4.setText("10");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jProgressBarwater.setBackground(new java.awt.Color(0, 153, 255));
        jProgressBarwater.setForeground(new java.awt.Color(255, 255, 255));
        jProgressBarwater.setValue(100);
        jProgressBarwater.setBorder(null);
        jProgressBarwater.setPreferredSize(new java.awt.Dimension(146, 8));
        jProgressBarwater.setString("water 100%");
        jProgressBarwater.setStringPainted(true);
        getContentPane().add(jProgressBarwater, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 210, 20));

        jProgressBarHp.setBackground(new java.awt.Color(255, 51, 51));
        jProgressBarHp.setForeground(new java.awt.Color(255, 255, 255));
        jProgressBarHp.setValue(100);
        jProgressBarHp.setBorder(null);
        jProgressBarHp.setOpaque(true);
        jProgressBarHp.setPreferredSize(new java.awt.Dimension(146, 8));
        jProgressBarHp.setString("food 100%");
        jProgressBarHp.setStringPainted(true);
        getContentPane().add(jProgressBarHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 210, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\sahee\\OneDrive\\Pictures\\โฟลเดอร์ใหม่\\Tenor-unscreen.gif")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 360, 310));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\sahee\\OneDrive\\Pictures\\โฟลเดอร์ใหม่\\gg.png")); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbuyingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbuyingActionPerformed
        buying nextFrame = new buying();
        nextFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btbuyingActionPerformed

    private void btwasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btwasteActionPerformed
        wasted nextFrame = new wasted();
        nextFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btwasteActionPerformed

    private void bttransportationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttransportationActionPerformed
        transport nextFrame = new transport();
        nextFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttransportationActionPerformed

    private void btlivingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlivingActionPerformed
        living nextFrame = new living();
        nextFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btlivingActionPerformed

    private void btfoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfoodActionPerformed
        Food nextFrame = new Food();
        nextFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btfoodActionPerformed

    private void historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyActionPerformed
        MainUI main = new MainUI();     // กลับไปหน้าแรก
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_historyActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mainmenu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bestreccord;
    private javax.swing.JButton btbuying;
    private javax.swing.JButton btfood;
    private javax.swing.JButton btliving;
    private javax.swing.JButton bttransportation;
    private javax.swing.JButton btwaste;
    private javax.swing.JLabel ecoin;
    private javax.swing.JButton history;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JProgressBar jProgressBarHp;
    private javax.swing.JProgressBar jProgressBarwater;
    // End of variables declaration//GEN-END:variables
}
