/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ecoapp;

/**
 *
 * @author sahee
 */
public class transport extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(transport.class.getName());

    /**
     * Creates new form transport
     */
    public transport() {
        initComponents();
        this.setLocationRelativeTo(null); // senter frame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ecoin = new javax.swing.JLabel();
        bestreccord = new javax.swing.JLabel();
        btback = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btpassenger = new javax.swing.JComboBox<>();
        btdistance = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btmodetransport = new javax.swing.JComboBox<>();
        btfrequency = new javax.swing.JComboBox<>();
        calculatefood = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        btbuying = new javax.swing.JButton();
        btwaste = new javax.swing.JButton();
        bttransportation = new javax.swing.JButton();
        btliving = new javax.swing.JButton();
        btfood = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ecoin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ecoin.setText("1000");
        getContentPane().add(ecoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        bestreccord.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bestreccord.setText("1000");
        getContentPane().add(bestreccord, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        btback.setIcon(new javax.swing.ImageIcon("C:\\Users\\sahee\\OneDrive\\Pictures\\โฟลเดอร์ใหม่\\HOme.png")); // NOI18N
        btback.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbackActionPerformed(evt);
            }
        });
        getContentPane().add(btback, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, 50));

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\sahee\\OneDrive\\Pictures\\โฟลเดอร์ใหม่\\SHOP.png")); // NOI18N
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 10, -1, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 0));
        jLabel6.setText("Freaguency (round/day)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        btpassenger.setBackground(new java.awt.Color(153, 255, 153));
        btpassenger.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btpassenger.setForeground(new java.awt.Color(51, 102, 0));
        btpassenger.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chicken", "beef", "pork", "vegetable", "rice" }));
        btpassenger.setOpaque(true);
        btpassenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpassengerActionPerformed(evt);
            }
        });
        getContentPane().add(btpassenger, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 120, -1));

        btdistance.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(btdistance, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 100, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 0));
        jLabel7.setText("mode of transport");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 0));
        jLabel8.setText("passengers");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 0));
        jLabel9.setText("distance (km/day)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        btmodetransport.setBackground(new java.awt.Color(153, 255, 153));
        btmodetransport.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btmodetransport.setForeground(new java.awt.Color(51, 102, 0));
        btmodetransport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chicken", "beef", "pork", "vegetable", "rice" }));
        btmodetransport.setOpaque(true);
        btmodetransport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmodetransportActionPerformed(evt);
            }
        });
        getContentPane().add(btmodetransport, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 120, -1));

        btfrequency.setBackground(new java.awt.Color(153, 255, 153));
        btfrequency.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btfrequency.setForeground(new java.awt.Color(51, 102, 0));
        btfrequency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chicken", "beef", "pork", "vegetable", "rice" }));
        btfrequency.setOpaque(true);
        btfrequency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfrequencyActionPerformed(evt);
            }
        });
        getContentPane().add(btfrequency, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 120, -1));

        calculatefood.setBackground(new java.awt.Color(51, 204, 0));
        calculatefood.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        calculatefood.setForeground(new java.awt.Color(255, 255, 255));
        calculatefood.setText("Calculate");
        calculatefood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatefoodActionPerformed(evt);
            }
        });
        getContentPane().add(calculatefood, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, 30));

        remove.setBackground(new java.awt.Color(255, 102, 102));
        remove.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        remove.setForeground(new java.awt.Color(255, 255, 255));
        remove.setText("remove");
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });
        getContentPane().add(remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, -1, 30));

        btbuying.setBackground(new java.awt.Color(0, 102, 51));
        btbuying.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btbuying.setForeground(new java.awt.Color(255, 255, 255));
        btbuying.setText("BUYING");
        btbuying.setActionCommand("TRANSPORT");
        btbuying.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbuyingActionPerformed(evt);
            }
        });
        getContentPane().add(btbuying, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 130, 50));

        btwaste.setBackground(new java.awt.Color(0, 102, 51));
        btwaste.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btwaste.setForeground(new java.awt.Color(255, 255, 255));
        btwaste.setText("WASTE");
        btwaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btwasteActionPerformed(evt);
            }
        });
        getContentPane().add(btwaste, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, 80, 50));

        bttransportation.setBackground(new java.awt.Color(0, 102, 51));
        bttransportation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bttransportation.setForeground(new java.awt.Color(255, 255, 255));
        bttransportation.setText("TRANSPORT");
        bttransportation.setEnabled(false);
        bttransportation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttransportationActionPerformed(evt);
            }
        });
        getContentPane().add(bttransportation, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 110, 50));

        btliving.setBackground(new java.awt.Color(0, 102, 51));
        btliving.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btliving.setForeground(new java.awt.Color(255, 255, 255));
        btliving.setText("LIVING");
        btliving.setActionCommand("TRANSPORT");
        btliving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlivingActionPerformed(evt);
            }
        });
        getContentPane().add(btliving, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 90, 50));

        btfood.setBackground(new java.awt.Color(0, 102, 51));
        btfood.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btfood.setForeground(new java.awt.Color(255, 255, 255));
        btfood.setText("FOOD");
        btfood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfoodActionPerformed(evt);
            }
        });
        getContentPane().add(btfood, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 80, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\sahee\\OneDrive\\Pictures\\โฟลเดอร์ใหม่\\TRANSPORT.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbackActionPerformed
        mainmenu main = new mainmenu();     // กลับไปหน้าแรก
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btbackActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btpassengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpassengerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btpassengerActionPerformed

    private void btmodetransportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmodetransportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btmodetransportActionPerformed

    private void btfrequencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfrequencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btfrequencyActionPerformed

    private void calculatefoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatefoodActionPerformed
        String selectedFood = btpassenger.getSelectedItem().toString();
        double efType;
        switch (selectedFood) {
            case "chicken":
            efType = 6.9;
            break;
            case "beef":
            efType = 27.0;
            break;
            case "pork":
            efType = 12.1;
            break;
            case "vegetable":
            efType = 2.0;
            break;
            default:
            efType = 0.0;
        }
        System.out.print(efType);
    }//GEN-LAST:event_calculatefoodActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeActionPerformed

    private void btbuyingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbuyingActionPerformed
        buying nextFrame = new buying();
        nextFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btbuyingActionPerformed

    private void btwasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btwasteActionPerformed
        wasted nextFrame = new wasted();
        nextFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btwasteActionPerformed

    private void bttransportationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttransportationActionPerformed
        transport nextFrame = new transport();
        nextFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttransportationActionPerformed

    private void btlivingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlivingActionPerformed
        living nextFrame = new living();
        nextFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btlivingActionPerformed

    private void btfoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfoodActionPerformed
        Food nextFrame = new Food();
        nextFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btfoodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new transport().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bestreccord;
    private javax.swing.JButton btback;
    private javax.swing.JButton btbuying;
    private javax.swing.JSpinner btdistance;
    private javax.swing.JButton btfood;
    private javax.swing.JComboBox<String> btfrequency;
    private javax.swing.JButton btliving;
    private javax.swing.JComboBox<String> btmodetransport;
    private javax.swing.JComboBox<String> btpassenger;
    private javax.swing.JButton bttransportation;
    private javax.swing.JButton btwaste;
    private javax.swing.JButton calculatefood;
    private javax.swing.JLabel ecoin;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton remove;
    // End of variables declaration//GEN-END:variables
}
